---
title: "Data Manipulation"
author: "Yaxuan Deng"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
```

Let's import the datasets

```{r}
litters_df <- 
  read_csv("data_import_examples/FAS_litters.csv",na=c("NA",".",""))
litters_df <- 
  janitor::clean_names(litters_df)

pups_df <- 
  read_csv("data_import_examples/FAS_pups.csv",skip = 3,na = c("NA",".",""))
pups_df <- 
  janitor::clean_names(pups_df)
```
## select

'select' selects variables from my dataframes

```{r}
select(litters_df, group, litter_number, gd0_weight, pups_born_alive)
```

select a range

```{r}
select(litters_df,group:gd_of_birth)
```

select by removal

```{r}
select(litters_df,-group)
select(litters_df,-group:gd_of_birth)
```

select by prefix

```{r}
select(litters_df,group,starts_with("gd"))
```

rearrange by selecting

```{r}
select(litters_df,starts_with("gd"),group)
select(litters_df,litter_number,everything())
```

```{r}
relocate(litters_df,litter_number)
```


rename by selecting

```{r}
select(litters_df,GROUP = group,everything())
rename(litters_df,GROUP = group)
```
what if i only select one variable?

```{r}
select(litters_df,group)
pull(litters_df,group)
```

```{r}
select(pups_df, sex,pd_ears)
```

## filter

use 'filter()' to filter out rows

```{r}
filter(litters_df,gd_of_birth == 20, pups_born_alive == 6)
```

look for more than two pups alive

```{r}
filter(litters_df,pups_born_alive > 5)
filter(litters_df,pups_born_alive >= 5)
filter(litters_df,pups_born_alive <= 5)
```

look for non-matches

```{r}
filter(litters_df,pups_born_alive != 6)
```

match to a set

```{r}
filter(litters_df,group %in% c("Con7","Con8"))
```

filter out missing rows with 'drop_na()'

```{r}
drop_na(litters_df)
drop_na(litters_df,gd0_weight)
```
```{r}
filter(pups_df,sex == 1)
```

