---
title: "Simple document"
output: html_document
---

I'm an R Markdown document! 

# Section 1

Here's a **code chunk** that samples from 
a _normal distribution_:

```{r}
samp = rnorm(100)
length(samp)
```

# Section 2

I can take the mean of the sample, too!
The mean is `r mean(samp)`.

```{r}
library(tidyverse)
library(readxl)
```
Let's import a dataset.

```{r}
litters_df = 
  read_csv("data_import_examples/FAS_litters.csv")
```
```{r}
names(litters_df)
```

```{r}
litters_df <- 
  janitor::clean_names(litters_df)
```

```{r}
litters_df
```

```{r}
skimr::skim(litters_df)
```

## fix missingness

```{r}
litters_df <- 
  read_csv("data_import_examples/FAS_litters.csv",na = c("NA",".",""))
```
```{r}
pups_df <- 
  read_csv("data_import_examples/FAS_pups.csv",skip = 3,na = c("NA",".",""))
pups_df <- 
  janitor::clean_names(pups_df)
```
## excel

```{r}
mlb_df <- read_excel("data_import_examples/mlb11.xlsx")
```

import LotR word counts

```{r}
fotr_df <- 
  read_excel("data_import_examples/LotR_Words.xlsx",range = "B3:D6")
```

